/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes.pbo;

/**
 *
 * @author this.naff
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuBuku extends javax.swing.JFrame {

    /**
     * Creates new form MenuBuku
     */
    public Statement st;
    public ResultSet rs;
    
    public DefaultTableModel tabModel;
    Connection cn = Koneksi.Koneksi();
    
    
    public void buku() {
        Object[] buku = {
          "ID Buku", "Judul", "Pengarang", "Penerbit"
        };
        tabModel = new DefaultTableModel(null, buku);
        tblDataBuku.setModel(tabModel);
    }

  public void tampilData(String where) {
    try {
      st = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
      tabModel.getDataVector().removeAllElements();
      tabModel.fireTableDataChanged();
      rs = st.executeQuery("SELECT * FROM buku " + where);

      while (rs.next()) {
        Object[] data = {
          rs.getString("kodeBuku"),
          rs.getString("judulBuku"),
          rs.getString("pengarang"),
          rs.getString("penerbit"),
        };

          tabModel.addRow(data);
      }
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                  "Kesalahan", JOptionPane.WARNING_MESSAGE);
    }
  }
    
  
  public void reset(){
      txtIdBuku.setText("");
      txtJudulBuku.setText("");
      txtPengarang.setText("");
      txtPenerbit.setText("");
      txtIdBuku.requestFocus();
      Ai();
      
      btnSave.setEnabled(true);
      btnCancel.setEnabled(true);
      btnDelete.setEnabled(true);
      btnUpdate.setEnabled(true);
  }
  
  public void Ai(){
      try {
          Koneksi.Koneksi();
          rs = st.executeQuery("SELECT MAX(right(kodeBuku,5)) FROM buku");
          while(rs.next()){
              if(rs.first()== false){
                  txtIdBuku.setText("BK-00001");
              }else{
                  rs.last();
                  int autoId = rs.getInt(1) + 1;
                  String idBuku = String.valueOf(autoId);
                  int noLong = idBuku.length();
                  for (int i = 0; i < 5-noLong; i++) {
                      idBuku = "0" + idBuku;
                  }
                  txtIdBuku.setText("BK-" + idBuku);
              }
              
          }
      } catch(Exception e) {
          JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                  "Kesalahan", JOptionPane.WARNING_MESSAGE);
      }      
  }
    
    
    public MenuBuku() {
        initComponents();
        buku();
        tampilData("");
        Ai();
        txtIdBuku.setEnabled(false);
        transparan();
        
        this.setTitle("Data Buku");
    }

    public void transparan(){
        btnSave.setFocusPainted(false);
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setOpaque(false);
        
        btnUpdate.setFocusPainted(false);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setOpaque(false);
        
        btnDelete.setFocusPainted(false);
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setOpaque(false);
        
        btnCancel.setFocusPainted(false);
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setOpaque(false);
        
        txtIdBuku.setOpaque(false);
        txtJudulBuku.setOpaque(false);
        txtPenerbit.setOpaque(false);
        txtPengarang.setOpaque(false);
        
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtJudulBuku = new javax.swing.JTextField();
        txtPengarang = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataBuku = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtIdBuku = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJudulBuku.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtJudulBuku.setBorder(null);
        getContentPane().add(txtJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 620, 30));

        txtPengarang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPengarang.setBorder(null);
        getContentPane().add(txtPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 630, 20));

        txtPenerbit.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPenerbit.setBorder(null);
        getContentPane().add(txtPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 630, 30));

        tblDataBuku.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblDataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDataBuku);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 720, 140));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/btn_save.png"))); // NOI18N
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 100, 60));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/btn_update.png"))); // NOI18N
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 100, 60));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/btn_delete.png"))); // NOI18N
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 100, 60));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/btn_cancel.png"))); // NOI18N
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 100, 60));

        txtIdBuku.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtIdBuku.setText("Kode Otomatis");
        getContentPane().add(txtIdBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/Data Buku.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
        st = cn.createStatement();
        st.executeUpdate("UPDATE buku set " 
            + "kodeBuku='"       + txtIdBuku.getText() + "', "
            + "judulBuku='"      + txtJudulBuku.getText() + "', "
            + "pengarang='"   + txtPengarang.getText()+ "', "
            + "penerbit='"    + txtPenerbit.getText() + "' WHERE "
            + "kodeBuku='"      + txtIdBuku.getText() + "'");
        tampilData("");
        JOptionPane.showMessageDialog(null, "Update Berhasil");
        reset();
      } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                  "Kesalahan", JOptionPane.WARNING_MESSAGE);
      }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
        st = cn.createStatement();
        st.executeUpdate("INSERT INTO buku VALUES('" + txtIdBuku.getText() + "','"
            + txtJudulBuku.getText() + "','"
            + txtPengarang.getText()+ "','"
            + txtPenerbit.getText()+ "')");
        tampilData("");
        JOptionPane.showMessageDialog(null, "Simpan Berhasil");
        reset();
      } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                  "Kesalahan", JOptionPane.WARNING_MESSAGE);
      }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataBukuMouseClicked
        // TODO add your handling code here:
        txtIdBuku.setText(tblDataBuku.getValueAt(tblDataBuku.getSelectedRow(), 0).toString());
        txtJudulBuku.setText(tblDataBuku.getValueAt(tblDataBuku.getSelectedRow(), 1).toString());
        txtPengarang.setText(tblDataBuku.getValueAt(tblDataBuku.getSelectedRow(), 2).toString());
        txtPenerbit.setText(tblDataBuku.getValueAt(tblDataBuku.getSelectedRow(), 3).toString());
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblDataBukuMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int jawab;

            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM buku WHERE kodeBuku='"
                    + tabModel.getValueAt(tblDataBuku.getSelectedRow(), 0) + "'");
                tampilData("");
                reset();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                  "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuBuku().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblDataBuku;
    private javax.swing.JLabel txtIdBuku;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPengarang;
    // End of variables declaration//GEN-END:variables
}
