/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes.pbo;

/**
 *
 * @author this.naff
 */

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javafx.scene.control.PasswordField;
import javax.swing.JOptionPane;

public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */    
     // deklarasi
        public Statement st;
        public ResultSet rs;
        Connection con = Koneksi.Koneksi();
        
    
    public MenuUtama() {
        initComponents();
        //tampilId();
        transparan();
        
        this.setTitle("- MyLibrary -");
    }
    

    public void admin(){
        btnPeminjaman.setVisible(false);
        btnPengembalian.setVisible(false);
    }
    
    public void petugas(){
        btnPetugas.setVisible(false);
    }

    public void transparan(){
        btnPetugas.setFocusPainted(false);
        btnPetugas.setBorderPainted(false);
        btnPetugas.setContentAreaFilled(false);
        btnPetugas.setOpaque(false);
        
        btnBuku.setFocusPainted(false);
        btnBuku.setBorderPainted(false);
        btnBuku.setContentAreaFilled(false);
        btnBuku.setOpaque(false);
        
        btnPeminjaman.setFocusPainted(false);
        btnPeminjaman.setBorderPainted(false);
        btnPeminjaman.setContentAreaFilled(false);
        btnPeminjaman.setOpaque(false);
        
        btnPengembalian.setFocusPainted(false);
        btnPengembalian.setBorderPainted(false);
        btnPengembalian.setContentAreaFilled(false);
        btnPengembalian.setOpaque(false);
        
        btnLogout.setFocusPainted(false);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setOpaque(false);
        
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPetugas = new javax.swing.JButton();
        btnBuku = new javax.swing.JButton();
        btnPeminjaman = new javax.swing.JButton();
        btnPengembalian = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/btnPetugas.png"))); // NOI18N
        btnPetugas.setBorder(null);
        btnPetugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPetugasMouseClicked(evt);
            }
        });
        btnPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetugasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 140, 140));

        btnBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/btnBuku.png"))); // NOI18N
        btnBuku.setBorder(null);
        btnBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBukuMouseClicked(evt);
            }
        });
        btnBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 140, 140));

        btnPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/btnPeminjaman.png"))); // NOI18N
        btnPeminjaman.setBorder(null);
        btnPeminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeminjamanMouseClicked(evt);
            }
        });
        getContentPane().add(btnPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 140, 140));

        btnPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/btnPengembalian.png"))); // NOI18N
        btnPengembalian.setBorder(null);
        btnPengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseClicked(evt);
            }
        });
        btnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 140, 140));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/logout menu.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 100, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pbo/assets/mnUtama.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBukuActionPerformed

    private void btnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPengembalianActionPerformed

    private void btnPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPetugasActionPerformed

    private void btnPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPetugasMouseClicked
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
    }//GEN-LAST:event_btnPetugasMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBukuMouseClicked
        // TODO add your handling code here:
        new MenuBuku().setVisible(true);
    }//GEN-LAST:event_btnBukuMouseClicked

    private void btnPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeminjamanMouseClicked
        // TODO add your handling code here:
        new Peminjaman().setVisible(true);
    }//GEN-LAST:event_btnPeminjamanMouseClicked

    private void btnPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseClicked
        // TODO add your handling code here:
        new Pengembalian().setVisible(true);
    }//GEN-LAST:event_btnPengembalianMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuUtama().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPeminjaman;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JButton btnPetugas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
